name: AZ Blue Website - Cross-Browser Testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run tests daily at 6 AM UTC
    - cron: "0 6 * * *"

jobs:
  smoke-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run Smoke tests (Core functionality)
        run: |
          npx playwright test --project=${{ matrix.browser }} \
            -g "should load homepage successfully|should load page within acceptable time|should have secure HTTPS connection" \
            --reporter=line

      - name: Upload smoke test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-test-results-${{ matrix.browser }}
          path: |
            test-results/
            playwright-report/
          retention-days: 7

  full-test:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    needs: smoke-test
    if: github.event_name == 'schedule' || contains(github.event.head_commit.message, '[full-test]')

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run Full test suite
        run: npx playwright test --project=${{ matrix.browser }} --max-failures=10

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-results-${{ matrix.browser }}
          path: |
            test-results/
            playwright-report/
          retention-days: 30

  mobile-test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: smoke-test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium webkit

      - name: Run Mobile smoke tests
        run: |
          npx playwright test --project="Mobile Chrome" --project="Mobile Safari" \
            -g "should load homepage successfully|should show mobile-optimized layout" \
            --reporter=line

      - name: Upload mobile test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-mobile-results
          path: |
            test-results/
            playwright-report/
          retention-days: 30

  performance-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: smoke-test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Performance tests
        run: |
          npx playwright test --project=chromium performance.spec.js \
            -g "should load page within acceptable time|should have good Core Web Vitals" \
            --reporter=line

      - name: Upload performance test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-test-results
          path: |
            test-results/
            playwright-report/
          retention-days: 30

  generate-report:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [smoke-test, mobile-test, performance-test]
    if: always()

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-test-results

      - name: Merge test results
        run: |
          mkdir -p merged-results/test-results
          mkdir -p merged-results/playwright-report
          find all-test-results -name "*.json" -exec cp {} merged-results/test-results/ \; || true
          find all-test-results -name "*.html" -exec cp {} merged-results/playwright-report/ \; || true

      - name: Upload merged results
        uses: actions/upload-artifact@v4
        with:
          name: complete-test-report
          path: merged-results/
          retention-days: 30

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: merged-results/playwright-report
